# Conda environment

name: viscoin

channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults

dependencies:
  - python=3.12

  # Deep learning libraries
  - pytorch>=2.5.0
  - torchvision>=0.20.0
  - transformers>=4.46.0
  - pillow
  - tqdm
  - numpy
  - lpips
  - openai-clip
  - opencv

  # Utilities
  - click
  - matplotlib
  - ninja # Required to build custom StyleGAN plugins
  - kagglehub
